vacp2p/zerokit

- rln/Cargo.toml
- rln/src/protocol.rs
- rln/src/utils.rs
Seems to do the trick, previously problems with `k256`, `signature` etc versions.
> fix(rln): Fix CI by updating ethers dependency

- rln/Cargo.toml
This is added to also generate a static library when building RLN
> chore(rln): add "staticlib" to crate-type in Cargo.toml

- rln/src/circuit.rs
- rln/src/ffi.rs
- rln/src/lib.rs
- rln/src/public.rs
Allows passing the wasm, zkey and verification key data as buffers, instead of using a path to a folder.
This is useful when you want to have this data embedded in a program / library, to not deal with paths to the resource folders
Required by:
- https://github.com/status-im/go-zerokit-rln/pull/1 (resources were embedded in https://github.com/status-im/go-zerokit-rln/tree/6762111dcbad7e858018e158d5162cac2b2b4427/rln/resources)
> feat(RLN): add `new_with_params`

- CHANGELOG.md
Initial release
Closes https://github.com/vacp2p/zerokit/issues/31 (plus comms)
> docs: Add CHANGELOG for v0.1 release

- CHANGELOG.md
- rln/src/ffi.rs
- rln/src/public.rs
This PR allows the following feature - https://github.com/status-im/nwaku/issues/1266.
Changes the C FFI of `set_leaves` to `init_tree_with_leaves`, and adds a new function called `set_leaves_from`, which `init_tree_with_leaves` uses internally, with starting index 0.
> feat(rln): ability to set leaves from a given index

- rln/src/ffi.rs
- rln/src/public.rs
- utils/src/merkle_tree/merkle_tree.rs
Included in this PR:
- `set_range` implemented for OptimalMerkleTree
- `set_leaves_from` uses `set_range`
- `set_range` of OptimalMerkleTree and FullMerkleTree now check the length of input hashes/leaves and compare to size of the tree
Misc:
- fix(rln): throw if attempting to insert out of bounds
- chore(rln): better error msg
> fix(rln): throw if attempting to insert out of bounds

- .github/workflows/nightly-release.yml
Exclude rln-wasm compilation in linux and macos steps
> fix(ci): exclude rln-wasm since it has its own step now

- semaphore/Cargo.toml
ark-circom with rev [746d232](https://github.com/gakonst/ark-circom/commit/746d2329e94e493560a53c41938c329d735d54ed) breaks CI for us, preventing nightly releases. This PR bumps the version of ark-circom we use back to before the commit which causes 
this issue - [e226f90](https://github.com/gakonst/ark-circom/commit/e226f90591e16429f3001edf5dfb72801fc8b6f9)
! This is a temporary fix and will need revisiting after it's fixed upstream !
> fix(semaphore): revert ark-circom dependency

- .github/workflows/nightly-release.yml
Nightly release CI is failing - https://github.com/vacp2p/zerokit/actions/runs/4299225323
> fix(ci): nightly release

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
- Cross.toml
- Makefile
- README.md
Updates CI to include -
- Caching for dependencies
- Use `make installdeps` instead of manually installing submodules
- Use `cross-rs` to cross-compile for different targets
> feat(ci): cross-compile release assets, cache deps

- rln/src/circuit.rs
std::path::Path is unused in the wasm context, therefore, moved the import to the cfg_if block
> fix(rln): move std::path to cfg_if block

- .github/workflows/nightly-release.yml
Unsure why github converted prereleases to drafts in the default behaviour of 
release creation using the gh cli, this pr fixes that.
> fix(ci): force draft=false for nightly releases

- rln/Cargo.toml
Continuing the follow up described in https://github.com/vacp2p/zerokit/pull/147
> feat(rln): make pmtree the default tree used

- Cargo.lock
- rln-wasm/Cargo.toml
- rln/src/protocol.rs
- rln/src/public.rs
- rln/src/utils.rs
`usize::from_le_bytes` will take an array of length 2, 4 or 8 bytes depending on the target pointer size. Since wasm is a 32b platform, it will take 4 bytes instead of the 8 bytes defined by the protocol, so there was a failure while reading serialized values due to the number of bytes read being incorrect. I also update version rln-wasm to 0.0.9 (npm package needs to be updated to include this fix)
> fix: u64 to usize conversion

- Cargo.lock
- rln/src/pm_tree_adapter.rs
- utils/Cargo.toml
- utils/src/merkle_tree/full_merkle_tree.rs
- utils/src/merkle_tree/merkle_tree.rs
- utils/src/merkle_tree/optimal_merkle_tree.rs
- utils/src/pm_tree/sled_adapter.rs
- utils/tests/merkle_tree.rs
Allows insertions and deletions in the same batch operation.
Note: deletion is just zeroing out a given index
- feat: batch ops in ZerokitMerkleTree
Follow up PR:
> combined batch operations (insert + delete)

- Cargo.lock
- rln/src/ffi.rs
- rln/src/public.rs
- rln/tests/ffi.rs
Follow up PR of https://github.com/vacp2p/zerokit/pull/160
> feat(rln): public, ffi for atomic ops

- .github/workflows/ci.yml
- rln-wasm/tests/rln-wasm.rs
Unwrap result values in `rln-wasm` tests due to changed function signature
Fix CI, particularly `rl-wasm` tests were not being run
> fix: wasm tests and ci

- Cargo.lock
- utils/Cargo.toml
- utils/README.md
- utils/benches/merkle_tree_benchmark.rs
- feat(utils): initialize benchmarks
- docs(utils): benchmark instructions
This PR solves a part of #89
example of the report generated -
> feat(utils): initialize benchmarks

- Cargo.lock
- rln/Cargo.toml
- rln/Makefile.toml
- rln/benches/pmtree_benchmark.rs
- utils/Makefile.toml
Closes https://github.com/vacp2p/zerokit/issues/89
pmtree using sled vs in-memory omt
> feat(rln): pmtree benchmarks

- rln/Cargo.toml
- utils/Cargo.toml
To allow criterion to be discovered by cargo
> fix(cargo.toml): bench=false

- .github/workflows/ci.yml
Benchmarks should only run in PRs so they have a base branch to compare
> fix(ci): run benchmarks only in PRs

- rln/src/pm_tree_adapter.rs
tuning sled db's configuration 
we are tuning for infrequent writes (once every 12 sec), and for very frequent reads
Closes https://github.com/vacp2p/zerokit/issues/151
These changes allow the clients to run their own benchmarks with their specific configurations.
> test(rln): sled db config change

- rln/src/pm_tree_adapter.rs
Fixes an edge case where the user erroneously passes in temporary = true with a valid path
> fix(rln): error out when temporary=true and path is exists

- rln/src/ffi.rs
- rln/src/public.rs
- rln/tests/ffi.rs
Exposes the `get_leaf` fn to the public and ffi api's
> feat(rln): get_leaf ffi and public api

- rln/src/public.rs
This PR resolves an error in which downstream libs were not able to pass a custom tree_config, this was due to using `as_str`, instead of 
`to_string`, which resulted in the default config to be used.
> fix(rln): tree_config parsing

- Cargo.lock
- semaphore/Cargo.toml
- utils/src/poseidon/poseidon_constants.rs
updates ethers-core to latest head
> chore: bump ethers-core

- semaphore/Cargo.toml
Use crates.io version of ethers-rs instead of github
> chore: use crates.io dep of ethers-rs

- Cargo.lock
- rln/src/ffi.rs
- rln/src/pm_tree_adapter.rs
- rln/src/public.rs
- utils/Cargo.toml
- utils/src/merkle_tree/full_merkle_tree.rs
- utils/src/merkle_tree/merkle_tree.rs
- utils/src/merkle_tree/optimal_merkle_tree.rs
- utils/src/pm_tree/sled_adapter.rs
this should allow applications to handle the lifecycle and gracefully close the connection to the db
> feat(rln): close db connection before dropping rln object

- Cargo.lock
- utils/Cargo.toml
Bumps pmtree to avoid unwrapping on values that don't exist at the time of db load
> chore(utils): bump pmtree rev

- Cargo.lock
- multiplier/Cargo.toml
- private-settlement/Cargo.toml
- rln-cli/Cargo.toml
- rln/Cargo.toml
- semaphore/Cargo.toml
- utils/Cargo.toml
@tyshko-rostyslav, could you update the release on crates.io with these tags?
> fix(crates): version tags

- rln/src/hashers.rs
Fixes the docs in rln/src/hashers.rs
> chore: docs cleanup

- rln-wasm/src/lib.rs
- rln/src/ffi.rs
- rln/src/public.rs
- rln/tests/ffi.rs
go-waku embeds the zkey, vk and circuit in the binary, so it's not necessary to rely on external files when deploying go-waku service node. It uses `new_with_params` to be able to pass these parameters. 
However, this function does not allow passing the merkle tree configuration. 
This PR adds a new parameter `tree_config`  which would allow passing this configuration. 
In a future PR, rln-wasm should be updated to receive a JSON (not a string containing a json) in the `wasm_new` function
> chore: accept tree_config in new_with_params

- rln/src/ffi.rs
This will help users of the library to get a reason on why a function is failing so we can help with support and reduce guesswork.
> feat: print to stderr any error obtained while executing functions via FFI

- rln-cli/src/main.rs
Due to https://github.com/vacp2p/zerokit/pull/199, rln-cli needed to be updated as well.
> fix(rln-cli): building in ci

- Cargo.lock
- utils/Cargo.toml
Now that the changes we require are upstream, using pmtree's crate
> chore: use pmtree instead of vacp2p_pmtree

- rln/src/ffi.rs
- rln/src/public.rs
Exposes a `seq_atomic_operation` api that uses the `next_index` under the hood to sequentially write to the tree
> chore(rln): expose seq_atomic_operation api

- utils/src/pm_tree/sled_adapter.rs
By using sled::open, we default to sled db's default config, which prevents us from opening the tree, thereby recreating it
also included: exp backoff for `WouldBlock` sled db io errors.
> fix(rln): use config.open instead of sled::open

- rln-cli/src/state.rs
- rln-wasm/tests/rln-wasm.rs
- rln/src/protocol.rs
- rln/src/public.rs
- Adds a range check before the proof generation to ensure the provided `messageId` is within the `userMessageLimit`
- Changed corresponding types to `Result`, as now they can emit errors
- Added function level documenation
> `message_id` range check

- rln/src/ffi.rs
- rln/tests/ffi.rs
Exposes the `leaves_set` api to allow consuming applications to have more metadata about the tree
> chore(rln): expose leaves_set api

- rln/src/pm_tree_adapter.rs
the `batch_insert` api is useful for multiple insertions while maintaining atomicity, but for single insertions, ruins performance - single insertions are atomic by 
nature so this pr circumvents it.
> fix(rln): if only a single insertion, dont use batch_insert

- .github/workflows/ci.yml
- rln/src/ffi.rs
- rln/src/public.rs
* Expose generate proof with witness ffi. This aims to allow other programming languages using the ffi to provide its own witness.
* Based on v0.3.4 so that its compatible with RLN v1. Ignore diff since the PR can't be based in a tag.
> Expose generate proof with witness ffi

- Cross.toml
Otherwise, it will complain about -lunwind not found due to reasons described in https://blog.rust-lang.org/2023/01/09/android-ndk-update-r25.html
> fix: add support to aarch64-linux-android

- rln/src/circuit.rs
- rln/src/pm_tree_adapter.rs
- rln/src/public_api_tests.rs
- rln/tests/ffi.rs
Previously, we returned an error if the metadata field was empty in the db. Now we return an empty vec so that clients can handle the error appropriately.
See: https://github.com/waku-org/nwaku/issues/2471
> chore(rln): return empty metadata if it doesnt exist

- utils/benches/merkle_tree_benchmark.rs
- utils/src/merkle_tree/merkle_tree.rs
- utils/tests/merkle_tree.rs
Few QoL traits to assist debugging.
> chore(rln): add QoL traits to the Hasher associated type in MerkleTree trait

- Cargo.toml
- rln-wasm/Cargo.toml
- rln-wasm/Makefile.toml
- **fix(rln-wasm): dont run benchmarks**
This PR excludes rln-wasm from default-members of the workspace and thereby allows `cargo bench` and `cargo make bench` to be ran from the root of the project.
thanks for the report @seemenkina
> fix(rln-wasm): dont run benchmarks

- .github/workflows/nightly-release.yml
Adds the arkzkey build to the nightly release workflow.
> chore(ci): add arkzkey feature to nightly assets

- Cargo.lock
- rln/Cargo.toml
- rln/benches/poseidon_tree_benchmark.rs
- rln/tests/ffi.rs
- rln/tests/poseidon_tree.rs
- rln/tests/protocol.rs
- rln/tests/public.rs
- utils/Cargo.toml
- utils/benches/merkle_tree_benchmark.rs
- utils/tests/merkle_tree.rs
- utils/tests/poseidon_constants.rs
Part of #237 
This PR includes:
- create benchmark from this test https://github.com/vacp2p/zerokit/blob/0521c7349e7aa36e25b43e4663def226451a7147/rln/tests/poseidon_tree.rs#L13
- add additional measurements for `FullMerkleTree` and `OptimalMerkleTree`  using `set_range` 
- extract common logic in tests/ffi.rs 
- refactor tests and benches
> chore(rln): tests and benchmarks review

- rln/src/protocol.rs
- rln/src/public.rs
> chore(rln) : Update documentation for rln-v2 to include new serde format

- rln/src/pm_tree_adapter.rs
- utils/src/merkle_tree/full_merkle_tree.rs
- utils/src/merkle_tree/optimal_merkle_tree.rs
Fixes override_range as was done in pmtree previously.
> fix(trees): inconsistencies in override_range

- rln/benches/pmtree_benchmark.rs
- rln/src/pm_tree_adapter.rs
- rln/src/public.rs
- rln/src/utils.rs
- rln/tests/poseidon_tree.rs
- rln/tests/public.rs
- utils/benches/merkle_tree_benchmark.rs
- utils/src/merkle_tree/full_merkle_tree.rs
- utils/src/merkle_tree/merkle_tree.rs
- utils/src/merkle_tree/optimal_merkle_tree.rs
- utils/tests/merkle_tree.rs
Part of #237 
In general everything is ready, tests that helped to find problems from #248  are commented out for now.
> Add function for checking indices of leaves which are set to zero

- rln/src/protocol.rs
- rln/src/public.rs
- rln/tests/protocol.rs
> Fix json serialization and update corresponding test

- Cargo.lock
- rln/Cargo.toml
- utils/Cargo.toml
Release v0.5.0
Published to crates.io: https://crates.io/crates/rln
> chore: Release

- rln/src/ffi.rs
- rln/src/public.rs
- rln/src/public_api_tests.rs
* Exposes `generate_rln_proof_with_witness` FFI, which allows to generate proofs with a custom witness.
* Similar as https://github.com/vacp2p/zerokit/pull/227/, which targeted RLN v1 but now targeting RLN v2.
> feat: expose custom witness ffi

- rln/Cargo.toml
- rln/benches/circuit_deser_benchmark.rs
- rln/benches/circuit_loading_benchmark.rs
- rln/src/circuit.rs
Benchmarking deserialization of verifying key. Need to merge this before https://github.com/vacp2p/zerokit/pull/257 to check if performance gains are being made.
> chore(rln): add verifying key deser benchmark

- .github/workflows/ci.yml
- Cargo.lock
- rln-cli/src/state.rs
- rln-wasm/src/lib.rs
- rln/Cargo.toml
- rln/benches/circuit_deser_benchmark.rs
- rln/benches/circuit_loading_benchmark.rs
- rln/src/circuit.rs
- rln/src/ffi.rs
- rln/src/public.rs
- rln/tests/ffi.rs
- rln/tests/protocol.rs
Refactored the RLN module to use static resources instead of dynamically loaded resources, removing lifetime dependencies. Additionally, updated several RLN object methods and tests for compatibility with these changes.
> chore(rln): refactor resource initialization

- Cargo.lock
- rln/Cargo.toml
- rln/src/circuit.rs
- rln/src/public.rs
Refactored the conditional compilation and import statements in the circuit.rs and updated method signatures to improve code clarity. Also, updated error handling in function vk_from_raw for better legibility.
> chore(rln): further refactoring of interface

- Cargo.lock
- rln/Cargo.toml
- utils/Cargo.toml
We initially crafted a github release v0.5.1 to test downstream, but since it works as intended, we bump packages and release to crates.io.
> chore(release): v0.5.1

- Cargo.lock
- rln-wasm/Cargo.toml
- rln-wasm/Makefile.toml
- rln-wasm/src/lib.rs
- rln/src/protocol.rs
- rln/src/public.rs
Fixes regression introduced in #241
> fix(rln-wasm): run tests again

- .github/workflows/nightly-release.yml
- Cargo.lock
- rln/Cargo.toml
- rln/src/ffi.rs
- rln/src/public.rs
- rln/src/public_api_tests.rs
- rln/tests/ffi.rs
- rln/tests/public.rs
- utils/Cargo.toml
UPD: Ready for review, integration into rln-wasm will be in follow PR 
Based on issues for [release 0.6.0](https://github.com/vacp2p/zerokit/issues/263)
Main changes: 
- Now when the flag `stateless` is specified, the tree for rln will be unavailable
- Added new constructors + took into consideration whether wasm32 is enabled or not :  
https://github.com/vacp2p/zerokit/blob/46dac03701549f59d8abb37a9d7afed51e38dba5/rln/src/public.rs#L118-L119 and https://github.com/vacp2p/zerokit/blob/46dac03701549f59d8abb37a9d7afed51e38dba5/rln/src/public.rs#L213-L214 and https://github.com/vacp2p/zerokit/blob/46dac03701549f59d8abb37a9d7afed51e38dba5/rln/src/public.rs#L265-L266
- The function to generate the proof without using tree was already written so I used it without changing the name …
> Stateless Feature

- .github/workflows/nightly-release.yml
- rln-cli/Cargo.toml
`rln-cli` is based on tree, so I remove this member from stateless build
> fix(CI): add condition for stateless feature

- Cargo.lock
- rln-wasm/Cargo.toml
- rln-wasm/src/lib.rs
- rln-wasm/tests/rln-wasm.rs
- rln/src/public.rs
Regarding Release v0.6.0 in issue #263 
Deprecate tree and correspond function from rln-wasm
> chore(rln-wasm): Make rln-wasm stateless

- .github/workflows/nightly-release.yml
Return the exception settings for run-cli. Also remove the build for the x32 architecture, because the new version of ark-circom depends on wasmer-wasix, which cannot be built on the x32 architecture.
See this issue for more details: https://github.com/vacp2p/zerokit/issues/282
> ci: fixed problem with nightly build after updating dependencies 

- Cargo.lock
- rln-cli/Makefile.toml
- rln/Cargo.toml
ark-circom update their branch to new dependency version and we can't support it right now. So I fix on previous commit
also during the local testing I find out that cargo make doesn't work correctly with new rln-cli examples (it calls "cargo" "build" "--all-features") and it's wrong behaviour
> fix: pin ark-circom version and solve local building problem

- rln-cli/src/main.rs
- rln/benches/circuit_loading_arkzkey_benchmark.rs
- rln/benches/circuit_loading_benchmark.rs
- rln/src/circuit.rs
- rln/src/ffi.rs
- rln/src/protocol.rs
- rln/src/public.rs
- rln/tests/ffi.rs
- rln/tests/protocol.rs
Brought back functionality that was removed during the migration to iden3 
- Modify circuit module to include graph data loading and calculation
- Update RLN struct to store graph data
- Adjust proof generation and FFI methods to use graph data
- Update benchmarks and tests to use sample size instead of measurement time
- Add new methods for graph data retrieval and handling
> feat(rln): Add custom iden3 graph data support for RLN

- rln-cli/src/examples/relay.rs
- rln/src/protocol.rs
- rln/src/public.rs
- rln/src/public_api_tests.rs
- rln/src/utils.rs
- rln/tests/ffi.rs
Review and refine utility functions to resolve #279:
- Update utility functions to the current version.
- Remove unused and commented-out code.
- Optimize some utility functions by using extend_from_slice() and pre-allocate size for Vec<u8>.
> fix(rln): review and refine utility functions in rln

- Cargo.lock
- rln/Cargo.toml
- rln/src/circuit.rs
- rln/src/iden3calc.rs
- rln/src/iden3calc/graph.rs
- rln/src/iden3calc/storage.rs
- rln/src/protocol.rs
- rln/src/utils.rs
- utils/Cargo.toml
While publishing the release on crate io it turned out that we can't use libraries without a version as it was for arc-circom. 
During the upgrade to the new version it was also discovered that it is possible to speed up input preparation for witness calculator by 4 times by switching from bigint to Fr:
it was also checked that it is also possible to use iden3 as a sub-module instead of copying code, but benchmarks showed that the new iden3 version with u256 calculations and subsequent conversion of the result to Fr is slower than the current implementation:
----
- Updated dependencies to their latest versions, including ark-ff, ark-bn254, ark-std, and others to 0.5.0.
- Refactored circuit and iden3calc modules to use Fr instead of BigInt for better type consistency.
- Improved utility …
> chore(rln): update dependencies and refactor code for compatibility

- Makefile
- README.md
- flake.lock
- flake.nix
It was requested to use newer version of Rust, so I added the https://github.com/oxalica/rust-overlay to have the most recent rust toolchain. Some of the dependencies needed to compile everything (`make all`) within shell weren't there so I had to add them. Also, within the Makefile the installation of `wasm-pack` using script downloaded from the internet was replaced with installation using cargo - same result but more safe.
> Add rust overlay and update shell dependencies

- .github/workflows/nightly-release.yml
- rln-cli/Cargo.toml
- rln-cli/README.md
- rln-cli/src/examples/relay.rs
- rln-cli/src/examples/stateless.rs
- rln-wasm/Cargo.toml
- rln-wasm/tests/browser.rs
- rln-wasm/tests/node.rs
- rln/Cargo.toml
- rln/Makefile.toml
- rln/src/lib.rs
- rln/src/poseidon_tree.rs
- rln/src/protocol.rs
- rln/src/public_api_tests.rs
- rln/tests/ffi.rs
- rln/tests/poseidon_tree.rs
- rln/tests/protocol.rs
- utils/Cargo.toml
- Resolved overlap between stateless and merkletree feature flags.
- Updated every testcase related to stateless feature.
- Added compile-time feature check to avoid feature overlap.
- Added --no-default-features for all builds in nightly-release.yml [(tested)](https://github.com/vacp2p/zerokit/actions/runs/16525062203).
> feat: resolve overlap between stateless and merkletree feature flags

- .github/workflows/ci.yml
- Makefile
- Add a CI rule to skip tests and benchmarks on draft pull requests
- Remove CMake installation from the installdeps command due to [this](https://github.com/actions/runner-images/issues/12912)
> chore: remove cmake due to CI error and skip tests and benchmarks on draft pull requests

- .github/workflows/nightly-release.yml
- Makefile
- rln-wasm/Makefile.toml
- rln-wasm/README.md
Currently, the new wasm-bindgen-cli version [causes CI to fail](https://github.com/vacp2p/zerokit/actions/runs/17699917161/job/50313998747), and it isn't needed for the parallel feature anymore.
So it's better to remove it from the codebase.
> chore(rln-wasm): remove wasm-bindgen-cli installation
