vacp2p/zerokit

- rln/src/circuit.rs
- rln/src/protocol.rs
- rln/src/utils.rs
Also, replaced unwraps with `?` in `ZKEY`
> refactor(RLN): use iterators instead of loops

- Cargo.toml
- private-settlement/Cargo.toml
- private-settlement/README.md
- private-settlement/src/lib.rs
The beginning of the development of the waku private settlement circuits and APIs.
> Initializes the private settlement package

- rln-wasm/Cargo.toml
- rln-wasm/src/lib.rs
> feat(rln-wasm): expose `set_leaves_from` and `init_tree_with_leaves`

- rln/src/ffi.rs
> feat(rln): Abstract ffi APIs structure with a helper function 

- rln/src/ffi.rs
- rln/src/public.rs
- rln/tests/ffi.rs
- rln/tests/public.rs
> feat(rln): expose poseidon to ffi

- CHANGELOG.md
> feat(v0.2): changelog

- .github/workflows/nightly-release.yml
- rln/Cargo.toml
- rln/src/circuit.rs
- rln/src/public.rs
- feat(rln): package resources into lib
- fix(rln): remove cdylib from target
> feat(rln): package rln w/ resources into a static lib

- multiplier/Cargo.toml
- semaphore/Cargo.toml
Temporary fix for failing CI ref: https://github.com/vacp2p/zerokit/actions/runs/4463841234/jobs/7839439039
ref issue: https://github.com/vacp2p/zerokit/issues/131
> fix(semaphore): use fixed rev

- .github/workflows/nightly-release.yml
> fix ci tag

- Makefile
- rln-wasm/Makefile.toml
- rln-wasm/README.md
> add wasm-strip to reduce size even more 

- Cargo.lock
- rln/Cargo.toml
- rln/src/pm_tree_adapter.rs
- rln/src/public.rs
- rln/tests/ffi.rs
- rln/tests/public.rs
- utils/Cargo.toml
- utils/src/merkle_tree/full_merkle_tree.rs
- utils/src/merkle_tree/merkle_tree.rs
- utils/src/merkle_tree/optimal_merkle_tree.rs
- utils/tests/merkle_tree.rs
Follow up PR of https://github.com/vacp2p/zerokit/pull/147
Commits:
- feat(rln): pass config in rln ffi
- fix: for rln-wasm
> feat(rln): ability to pass rln tree config in ffi

- rln-cli/src/commands.rs
- rln-cli/src/main.rs
> MVP CLI Proposal implementation: leaf and root interactions

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
- .github/workflows/sync-labels.yml
Compares and creates a comment with the benchmarks of each pr to avoid regressions
> feat(ci): compare benchmarks with master 

- rln-cli/src/commands.rs
- rln-cli/src/main.rs
> MVP CLI Proposal implementation: proof/verify functionality 

- Cargo.lock
- rln-cli/Cargo.toml
- rln-cli/src/config.rs
- rln-cli/src/main.rs
- rln-cli/src/state.rs
> CLI state between calls 

- rln-wasm/src/lib.rs
- rln-wasm/tests/rln-wasm.rs
- rln/src/public.rs
Follow up PR to https://github.com/vacp2p/zerokit/pull/178. Suggested by @richard-ramos to create a pr for the rln-wasm crate.
> feat(rln-wasm): set/get metadata api

- Cargo.lock
- utils/Cargo.toml
- chore(utils): bump pmtree rev
> chore(utils): bump pmtree rev

- rln-cli/src/commands.rs
- rln-cli/src/main.rs
- rln-cli/src/state.rs
Made needed changes to CLI, stopgapped by #201
> CLI fix for `tree_config_input`

- Cargo.lock
- semaphore/Cargo.toml
Among other things move to latest commit of `semaphore-rs`
> Semaphore update

- rln/src/pm_tree_adapter.rs
- rln/src/public.rs
- rln/tests/ffi.rs
Companion PR to #230 for rln-v1
> feat(rln-v1): return empty metadata if it doesnt exist

- Cargo.lock
- rln/Cargo.toml
- utils/Cargo.toml
- **chore: Release**
- **fix: rln version**
- **chore: Release**
> v0.4.3 release

- Cargo.lock
- rln/benches/pmtree_benchmark.rs
- rln/src/pm_tree_adapter.rs
- rln/src/public.rs
- rln/tests/poseidon_tree.rs
- rln/tests/public.rs
- utils/Cargo.toml
- utils/benches/merkle_tree_benchmark.rs
- utils/src/merkle_tree/full_merkle_tree.rs
- utils/src/merkle_tree/merkle_tree.rs
- utils/src/merkle_tree/optimal_merkle_tree.rs
- utils/tests/merkle_tree.rs
> Expose a public function to fetch the root of a subtree at level n

- .github/workflows/ci.yml
- .gitmodules
- Cargo.lock
- rln/Cargo.toml
mopro published a library release with arkzkey, so I replaced the submodule with that library 
Part of #237
> Replace arkzkey git submodule to library

- .github/workflows/nightly-release.yml
Fix error from nightly build: https://github.com/vacp2p/zerokit/actions/runs/10840811163/job/30104834868
> fix(CI): update actions version
